name: Build

on:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [18]
        os: [ubuntu-latest]

    steps:
      - name: Setup Git Config
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
          git config --global user.email "actions@gihub.com"
          git config --global user.name "gh-actions"
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 7.31.0
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
          cache: "pnpm"
      - run: pnpm i --frozen-lockfile
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Test & Build
        run: |
          pnpm build
        env:
          CI: true
